export const APPLICATION_GETALL = 'APPLICATION_GETALL';
export const APPLICATION_PERSIST = 'APPLICATION_PERSIST';
export const APPLICATION_DELETE = 'APPLICATION_DELETE';
export const APPLICATION_GETBYID = 'APPLICATION_GETBYID';